package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sync"

	"tailscale.com/tsnet"
)

const sunshineConfigTemplate = `# Auto-generated by AnyPortal — do not edit manually.
# This file is overwritten on every launch.

# Phase 2: strictly bind to localhost, routed via tsnet proxy.
bind_address = 127.0.0.1
address_family = ipv4
upnp = disabled
origin_web_ui_allowed = pc
`

func RunServer(cfg *Config, logWriter io.Writer, internalLog *log.Logger, meshIPChan chan<- string, exitChan <-chan struct{}) error {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	srv := &tsnet.Server{
		Hostname:  "anyportal-host",
		AuthKey:   cfg.AuthKey,
		Ephemeral: true,
		Dir:       filepath.Join(".", ".tsnet-anyportal-host"),
		Logf:      internalLog.Printf,
	}

	if err := os.MkdirAll(srv.Dir, 0700); err != nil {
		meshIPChan <- ""
		return fmt.Errorf("failed to create tsnet state directory: %w", err)
	}

	printStatus("Connecting to Tailscale mesh network...")

	status, err := srv.Up(ctx)
	if err != nil {
		meshIPChan <- ""
		return fmt.Errorf(
			"Tailscale authentication failed.\n\n"+
				"  Your auth key may be expired, already used, or invalid.\n"+
				"  Auth keys can only be used a limited number of times\n"+
				"  (default: 1 use for ephemeral keys).\n\n"+
				"  Fix: Generate a new key at https://login.tailscale.com/admin/settings/keys\n"+
				"       Update 'auth_key' in config.json and restart.\n\n"+
				"  Internal error: %w", err,
		)
	}
	_ = status

	ip4, _ := srv.TailscaleIPs()
	if !ip4.IsValid() {
		srv.Close()
		meshIPChan <- ""
		return fmt.Errorf(
			"Tailscale node started but no IPv4 address was assigned.\n"+
				"  This is unexpected. Check your Tailscale admin panel.\n"+
				"  The node may not have been fully registered",
		)
	}
	meshIP := ip4.String()
	printStatus("Mesh IP assigned: %s", meshIP)

	// Send Mesh IP to unblock main thread tray loop
	meshIPChan <- meshIP

	confPath := filepath.Join("core", "sunshine.conf")

	if err := os.MkdirAll("core", 0755); err != nil {
		srv.Close()
		return fmt.Errorf("failed to create core/ directory: %w", err)
	}

	if err := os.WriteFile(confPath, []byte(sunshineConfigTemplate), 0644); err != nil {
		srv.Close()
		return fmt.Errorf("failed to write sunshine.conf: %w", err)
	}
	internalLog.Printf("Wrote sunshine config to %s", confPath)

	var proxyWg sync.WaitGroup
	printStatus("Activating Server Userspace Reverse Proxy Engine...")
	StartServerProxy(ctx, srv, internalLog, &proxyWg)

	printStatus("Launching Sunshine encoder on 127.0.0.1...")

	sunshineExe := filepath.Join("core", "sunshine", "sunshine.exe")
	cmd := exec.CommandContext(ctx, sunshineExe, confPath)
	cmd.Stdout = logWriter
	cmd.Stderr = logWriter

	if err := cmd.Start(); err != nil {
		srv.Close()
		return fmt.Errorf(
			"Failed to launch Sunshine.\n\n"+
				"  Ensure that sunshine.exe exists at '%s'.\n"+
				"  Download the Sunshine Portable release from:\n"+
				"  https://github.com/LizardByte/Sunshine/releases\n\n"+
				"  Internal error: %w",
			sunshineExe, err,
		)
	}
	printStatus("✓ Ready. Sharing mesh target IP with your client terminal: %s", meshIP)
	printStatus("  First time? Open local browser to pair: https://127.0.0.1:47990")

	return supervise(cmd, srv, "Sunshine", exitChan, cancel, &proxyWg)
}

func supervise(cmd *exec.Cmd, srv *tsnet.Server, childName string, exitChan <-chan struct{}, cancel context.CancelFunc, wg *sync.WaitGroup) error {
	childDone := make(chan error, 1)
	go func() {
		childDone <- cmd.Wait()
	}()

	select {
	case <-exitChan:
		printStatus("Received quit signal. Shutting down...")

		printStatus("Stopping %s...", childName)
		if cmd.Process != nil {
			cmd.Process.Kill()
			<-childDone
		}

		printStatus("Tearing down proxy engine...")
		cancel()
		if wg != nil {
			wg.Wait()
		}

		printStatus("Disconnecting from Tailscale...")
		if err := srv.Close(); err != nil {
			printError("tsnet close error: %v", err)
		}

		printStatus("Shutdown complete.")
		return nil

	case err := <-childDone:
		defer cancel()
		if wg != nil {
			go wg.Wait()
		}
		defer srv.Close()

		if err != nil {
			return fmt.Errorf(
				"%s stopped unexpectedly.\n\n"+
					"  Check anyportal.log for details.\n"+
					"  Internal error: %w",
				childName, err,
			)
		}
		printStatus("%s exited cleanly.", childName)
		return nil
	}
}
